# Réseaux personnalisés
networks:
  roottrading-net:
    driver: bridge

# Volumes persistants
volumes:
  redis-data:
  kafka-data:
  zookeeper-data:
  db-data:

services:
  # Services d'infrastructure
  redis:
    image: redis:6-alpine
    container_name: roottrading-redis-1
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - roottrading-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: roottrading-zookeeper-1
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - roottrading-net

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: roottrading-kafka-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: unless-stopped
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z kafka 9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - roottrading-net

  db:
    image: timescale/timescaledb:latest-pg14
    container_name: roottrading-db-1
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
      POSTGRES_DB: ${PGDATABASE:-trading}
      PGDATA: /var/lib/postgresql/data/pgdata
      TIMESCALEDB_TELEMETRY: off
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - roottrading-net

  # Services d'application de base
  dispatcher:
    container_name: roottrading-dispatcher-1
    build:
      context: .  # Point sur le répertoire racine du projet
      dockerfile: dispatcher/Dockerfile  # Chemin vers le Dockerfile
    ports:
      - "5004:5004"
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5004/health').read()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - roottrading-net

  market_analyzer:
    container_name: roottrading-market-analyzer-1
    build:
      context: .
      dockerfile: market_analyzer/Dockerfile
    ports:
      - "5020:5020"
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
      - WAIT_FOR_DB=true
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
      dispatcher:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5020/health').read()"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - roottrading-net

  gateway:
    container_name: roottrading-gateway-1
    build:
      context: .  # Point sur le répertoire racine du projet
      dockerfile: gateway/Dockerfile  # Chemin vers le Dockerfile
    ports:
      - "5010:5010"
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5010/health').read()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - roottrading-net

  # Services de traitement
  analyzer:
    container_name: roottrading-analyzer-1
    build:
      context: .  # Point sur le répertoire racine du projet
      dockerfile: analyzer/Dockerfile  # Chemin vers le Dockerfile
    ports:
      - "5012:5012"
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
      - WAIT_FOR_DB=true
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5012/health').read()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - roottrading-net

  signal_aggregator:
    container_name: roottrading-signal-aggregator-1
    build:
      context: .  # Point sur le répertoire racine du projet
      dockerfile: signal_aggregator/Dockerfile  # Chemin vers le Dockerfile
    ports:
      - "5013:5013" # New: Health check port for signal_aggregator
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
      - WAIT_FOR_DB=true
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5013/health').read()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - roottrading-net

  trader:
    container_name: roottrading-trader-1
    build:
      context: .  # Point sur le répertoire racine du projet
      dockerfile: trader/Dockerfile  # Chemin vers le Dockerfile
    ports:
      - "5002:5002"
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
      - WAIT_FOR_DB=true
      - WAIT_FOR=dispatcher:5004,analyzer:5012
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 5002)); s.close()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - roottrading-net

  portfolio:
    container_name: roottrading-portfolio-1
    build:
      context: .  # Point sur le répertoire racine du projet
      dockerfile: portfolio/Dockerfile  # Chemin vers le Dockerfile
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
      - WAIT_FOR_DB=true
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 8000)); s.close()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    ports:
      - "8000:8000"  # API Portfolio
    networks:
      - roottrading-net

  coordinator:
    container_name: roottrading-coordinator-1
    build:
      context: .  # Point sur le répertoire racine du projet
      dockerfile: coordinator/Dockerfile  # Chemin vers le Dockerfile
    ports:
      - "5003:5003"
    environment:
      - WAIT_FOR_REDIS=true
      - WAIT_FOR_KAFKA=true
      - WAIT_FOR_DB=true
      - WAIT_FOR=trader:8080,portfolio:8000,
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 5003)); s.close()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - roottrading-net

  visualization:
    container_name: roottrading-visualization-1
    build:
      context: .
      dockerfile: visualization/Dockerfile
    ports:
      - "5009:5009"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=trading
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - VISUALIZATION_PORT=5009
    env_file: .env
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5009/api/health').read()"]
      interval: 180s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - roottrading-net
